
POST http://localhost:3001/api/authencication/signup
Content-Type: application/json

{
    "username": "Ebi",
    "password" : "password"
}

###

POST http://localhost:3001/api/authencication/login
Content-Type: application/json

{
    "username": "Ebi",
    "password" : "password"
}
